name = "BasicArithmetics"
uuid = "98d11411-5594-4b3c-95c3-c0a4e1934d79"
authors = ["Janes Luc Sanne <j.sanne@tu-berlin.de> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
